Hello, I am preparing a property in order to setup a debomatic machine
but  when I try to upload a package I get this error from debomatic

    DEBUG: Command '['schroot', '-l']' returned non-zero exit status 1
    Traceback (most recent call last):
    File "/usr/share/debomatic/Debomatic/process.py", line 197, in _finish
      raise e
    File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
      result = self.fn(*self.args, **self.kwargs)
    File "/usr/share/debomatic/Debomatic/build.py", line 525, in run
      self._build()
    File "/usr/share/debomatic/Debomatic/build.py", line 133, in _build
      self._setup_chroot()
    File "/usr/share/debomatic/Debomatic/build.py", line 395, in _setup_chroot
      chroots = check_output(['schroot', '-l'], stderr=fd)
    File "/usr/lib/python3.5/subprocess.py", line 316, in check_output
      **kwargs).stdout
    File "/usr/lib/python3.5/subprocess.py", line 398, in run
      output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['schroot', '-l']' returned non-zero exit status 1

so tried on my own

    :/etc/debomatic# schroot -l
    E: /etc/schroot/chroot.d/stretch-amd64-sbuild-propellor: [stretch-amd64-sbuild]: Required key ‘directory’ is missing

to my opinion the schroot config file generated by Sbuild property does something wrong.

Cheers

> [[done]]; I merged patches from spwhitton. --[[Joey]]
